### ISSUE TITLE
clean up plain language - Paul's suggestions

### ISSUE THREAD

**Issue by Rinapadua** [GBLSMA/docassemble-MAEvictionDefense#54]
~1. clicking on "I missed my first court date" doesn't generate any warning and just continues the interview 
2. On "reason for eviction" clicking on "I don't know" still allows other choices to be selected. Shouldn't "I don't know" clear any other choices?
3. Basis for fault only allows one choice; often notice will include several fault grounds~
4. Hearing/Answer date: I entered dates that were in the past; no warning was generated
~5. Type of subsidy: should include "other" since this is not an exhaustive list (maybe with a hint that these are the most common); also, only allows one choice but property can be tax credit and also involve a subsidy (strictly speaking, tax credit is not a subsidy)
6. Common defenses to subsidized housing. Wonder whether some hints should be here. E.g., right to meet with owner applies to HUD multi-family but not to Section 8 voucher. I understand that it's not possible to fully annotate every choice.
7. Termination of tenancy: typo There are right ways and a wrong ways 
8. Termination of tenancy: "The notice to quit has my name on it" This is defaulted to have the check. I think it's confusing to do it this way because it implies that it's a defense to have the tenant's name on the notice.  Same comment for the next two choices on this list.
9. Defenses for fault eviction: tracks same issue in 3. only one fault ground allowed
10. Waiver - signing recertification papers generally does not result in waiver
11. Lack of standing
If your landlord has “standing” it means that they are the correct person to evict you. Sometimes they may not be. The owner, or an attorney hired by the owner, has standing. If ownership hasn’t changed sometimes someone who will be the owner soon lacks the right to evict you.
Why do you have a new landlord?Select box
This is confusing. I think it makes sense to ask about change of ownership but the introductory paragraph about standing is confusing. It doesn't really relate to the new owner issue. Also, "an attorney hired by the owner" doesn't have standing. And the landlord may not be the same as the owner so there's an additional level of possible confusion there. 
12. Retaliation; same issues as 3; limited to one fault ground~
13. Foreclosure related defenses; bona fide tenant listed in two choices; not sure why
also not sure why "I am entitled to possession and damages" is a choice; it's also worded slightly differently further down on the list (If the substantive defense is selected, why would the tenant need to also select the "I am entitled to" box?)
~14. Sexual Harassment - the second choice doesn't follow the structure of the other choices~
~15. Protected Classes and Discrimination; I don't understand what "My landlord is not discriminating against me" means. It doesn't clear the other choices if selected although selecting "none of the above" does clear everything else. 
Also, not clear that landlord could be guilty of discrimination against a household member (uses "you")  
16. Bad Conditions: "List any problems with the apartment you live in now. Think about problems over the last 6 years, whether they are currently repaired or not. Your landlord will only be liable for problems that they knew about or should have known about."
Landlord/They (I know this is an issue of neutral pronoun but it grates. Maybe just me)
Suggest: "that the landlord knew about or that existed when I moved in or when the landlord bought the building."~
17. Interrogatories; I see question about security deposit but don't recall any question in interview about whether security deposit (or LMR)  was paid
~18 Pdf answer form (attached) : several paragraphs weren't numbered properly. Some letters repeated; others skipped; others used bullets 
19 Discovery form generated (attached) : (text in red below should be deleted)
No later than ten (10) days after you or your attorney receives this Request for Discovery, the court and the defendant must receive your responses to these questions and documents requested. Answers should be mailed or delivered to the defendant’s apartment
20. The generated discovery paragraph numbering is odd.~
21. I'm not able to get back into the interview. The links below (I think they're supposed to be links) don't work. Using the back button cleared all of my answers. I wasn't able to get back into the interview to make changes even though I had logged in.

**Comment by jpylephilalegal** [comment]
@Rinapadua @nonprofittechy -- regarding Number 4, "Hearing/Answer date: I entered dates that were in the past; no warning was generated," if you install version 0.2.56 of docassemble, you can use [`min`](https://docassemble.org/docs/fields.html#min) and [`max`](https://docassemble.org/docs/fields.html#max) with fields of `datatype: date`.  E.g.,
```
modules:
  - docassemble.base.util
---
question: |
  When is your hearing?
fields:
  - Hearing: hearing_date
    datatype: date
    min: |
      ${ today() }
    max: |
      ${ today().plus(months=12) }
---
mandatory: True
question: |
  Your hearing is on ${ hearing_date }.
```
